from google.appengine.ext import ndb
####### Entity Classes #######

class Sex(ndb.Model):
    male = ndb.IntegerProperty()
    female = ndb.IntegerProperty()

class Age(ndb.Model):
    male_under_5 = ndb.IntegerProperty()
    male_5_to_9 = ndb.IntegerProperty()
    male_10_to_14 = ndb.IntegerProperty()
    male_15_to_17 = ndb.IntegerProperty()
    male_18_and_19 = ndb.IntegerProperty()
    male_20 = ndb.IntegerProperty()
    male_21 = ndb.IntegerProperty()
    male_22_to_24 = ndb.IntegerProperty()
    male_25_to_29 = ndb.IntegerProperty()
    male_30_to_34 = ndb.IntegerProperty()
    male_35_to_39 = ndb.IntegerProperty()
    male_40_to_44 = ndb.IntegerProperty()
    male_45_to_49 = ndb.IntegerProperty()
    male_50_to_54 = ndb.IntegerProperty()
    male_55_to_59 = ndb.IntegerProperty()
    male_60_and_61 = ndb.IntegerProperty()
    male_62_to_64 = ndb.IntegerProperty()
    male_65_and_66 = ndb.IntegerProperty()
    male_67_to_69 = ndb.IntegerProperty()
    male_70_to_74 = ndb.IntegerProperty()
    male_74_to_79 = ndb.IntegerProperty()
    male_80_to_84 = ndb.IntegerProperty()
    male_over_85 = ndb.IntegerProperty()
    female_under_5 = ndb.IntegerProperty()
    female_5_to_9 = ndb.IntegerProperty()
    female_10_to_14 = ndb.IntegerProperty()
    female_15_to_17 = ndb.IntegerProperty()
    female_18_and_19 = ndb.IntegerProperty()
    female_20 = ndb.IntegerProperty()
    female_21 = ndb.IntegerProperty()
    female_22_to_24 = ndb.IntegerProperty()
    female_25_to_29 = ndb.IntegerProperty()
    female_30_to_34 = ndb.IntegerProperty()
    female_35_to_39 = ndb.IntegerProperty()
    female_40_to_44 = ndb.IntegerProperty()
    female_45_to_49 = ndb.IntegerProperty()
    female_50_to_54 = ndb.IntegerProperty()
    female_55_to_59 = ndb.IntegerProperty()
    female_60_and_61 = ndb.IntegerProperty()
    female_62_to_64 = ndb.IntegerProperty()
    female_65_and_66 = ndb.IntegerProperty()
    female_67_to_69 = ndb.IntegerProperty()
    female_70_to_74 = ndb.IntegerProperty()
    female_74_to_79 = ndb.IntegerProperty()
    female_80_to_84 = ndb.IntegerProperty()
    female_over_85 = ndb.IntegerProperty()
class Race(ndb.Model):
    white = ndb.IntegerProperty()
    black = ndb.IntegerProperty()
    american_indian_and_alaska_native = ndb.IntegerProperty()
    asian = ndb.IntegerProperty()
    native_hawaiian_and_other_pacific = ndb.IntegerProperty()
    other_race = ndb.IntegerProperty()
    hispanic_latino = ndb.IntegerProperty()

class State(ndb.Model):
    """ Model for a listing of state items """
    state = ndb.StringProperty()
    year  = ndb.IntegerProperty()
    source = ndb.StringProperty()
    sex = ndb.StructuredProperty(Sex)
    age = ndb.StructuredProperty(Age)
    race = ndb.StructuredProperty(Race) 
